module.exports = `Admiral,https://vignette.wikia.nocookie.net/animalcrossing/images/5/52/NH-Admiral_poster.png
Agent S,https://vignette.wikia.nocookie.net/animalcrossing/images/d/dd/NH-Agent_S_poster.png
Agnes,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e8/NH-Agnes_poster.png
Al,https://vignette.wikia.nocookie.net/animalcrossing/images/9/90/NH-Al_poster.png
Alfonso,https://vignette.wikia.nocookie.net/animalcrossing/images/0/0d/NH-Alfonso_poster.png
Alice,https://vignette.wikia.nocookie.net/animalcrossing/images/9/96/NH-Alice_poster.png
Alli,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e8/NH-Alli_poster.png
Amelia,https://vignette.wikia.nocookie.net/animalcrossing/images/9/9d/NH-Amelia_poster.png
Anabelle,https://vignette.wikia.nocookie.net/animalcrossing/images/b/bd/NH-Anabelle_poster.png
Anchovy,https://vignette.wikia.nocookie.net/animalcrossing/images/f/fc/NH-Anchovy_poster.png
Ankha,https://vignette.wikia.nocookie.net/animalcrossing/images/9/9a/NH-Ankha_poster.png
Angus,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e9/NH-Angus_poster.png
Anicotti,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e1/NH-Anicotti_poster.png
Annalisa,https://vignette.wikia.nocookie.net/animalcrossing/images/6/64/NH-Annalisa_poster.png
Annalise,https://vignette.wikia.nocookie.net/animalcrossing/images/2/26/NH-Annalise_poster.png
Antonio,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d0/NH-Antonio_poster.png
Apollo,https://vignette.wikia.nocookie.net/animalcrossing/images/7/78/NH-Apollo_poster.png
Apple,https://vignette.wikia.nocookie.net/animalcrossing/images/3/37/NH-Apple_poster.png
Astrid,https://vignette.wikia.nocookie.net/animalcrossing/images/3/3f/NH-Astrid_poster.png
Audie,https://vignette.wikia.nocookie.net/animalcrossing/images/a/ac/NH-Audie_poster.png
Aurora,https://vignette.wikia.nocookie.net/animalcrossing/images/3/33/NH-Aurora_poster.png
Ava,https://vignette.wikia.nocookie.net/animalcrossing/images/2/25/NH-Ava_poster.png
Avery,https://vignette.wikia.nocookie.net/animalcrossing/images/9/95/NH-Avery_poster.png
Axel,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c5/NH-Axel_poster.png
Baabara,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d0/NH-Baabara_poster.png
Bam,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b2/NH-Bam_poster.png
Bangle,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c7/NH-Bangle_poster.png
Barold,https://vignette.wikia.nocookie.net/animalcrossing/images/9/99/NH-Barold_poster.png
Bea,https://vignette.wikia.nocookie.net/animalcrossing/images/c/ca/NH-Bea_poster.png
Beardo,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c7/NH-Beardo_poster.png
Beau,https://vignette.wikia.nocookie.net/animalcrossing/images/2/2a/NH-Beau_poster.png
Becky,https://vignette.wikia.nocookie.net/animalcrossing/images/e/ec/NH-Becky_poster.png
Bella,https://vignette.wikia.nocookie.net/animalcrossing/images/1/1e/NH-Bella_poster.png
Benedict,https://vignette.wikia.nocookie.net/animalcrossing/images/0/0e/NH-Benedict_poster.png
Benjamin,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5f/NH-Benjamin_poster.png
Bertha,https://vignette.wikia.nocookie.net/animalcrossing/images/3/3f/NH-Bertha_poster.png
Bettina,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a9/NH-Bettina_poster.png
Bianca,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e2/NH-Bianca_poster.png
Biff,https://vignette.wikia.nocookie.net/animalcrossing/images/2/2c/NH-Biff_poster.png
Big Top,https://vignette.wikia.nocookie.net/animalcrossing/images/c/ca/NH-Big_Top_poster.png
Bill,https://vignette.wikia.nocookie.net/animalcrossing/images/4/4c/NH-Bill_poster.png
Billy,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d3/NH-Billy_poster.png
Biskit,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c8/NH-Biskit_poster.png
Bitty,https://vignette.wikia.nocookie.net/animalcrossing/images/7/7c/NH-Bitty_poster.png
Blaire,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f3/NH-Blaire_poster.png
Blanche,https://vignette.wikia.nocookie.net/animalcrossing/images/1/18/NH-Blanche_poster.png
Bluebear,https://vignette.wikia.nocookie.net/animalcrossing/images/5/50/NH-Bluebear_poster.png
Bob,https://vignette.wikia.nocookie.net/animalcrossing/images/1/14/NH-Bob_poster.png
Bonbon,https://vignette.wikia.nocookie.net/animalcrossing/images/7/75/NH-Bonbon_poster.png
Bones,https://vignette.wikia.nocookie.net/animalcrossing/images/9/91/NH-Bones_poster.png
Boomer,https://vignette.wikia.nocookie.net/animalcrossing/images/1/12/NH-Boomer_poster.png
Boone,https://vignette.wikia.nocookie.net/animalcrossing/images/9/9c/NH-Boone_poster.png
Boots,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f3/NH-Boots_poster.png
Boris,https://vignette.wikia.nocookie.net/animalcrossing/images/5/54/NH-Boris_poster.png
Boyd,https://vignette.wikia.nocookie.net/animalcrossing/images/9/9d/NH-Boyd_poster.png
Bree,https://vignette.wikia.nocookie.net/animalcrossing/images/4/42/NH-Bree_poster.png
Broccolo,https://vignette.wikia.nocookie.net/animalcrossing/images/1/10/NH-Broccolo_poster.png
Broffina,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c9/NH-Broffina_poster.png
Bruce,https://vignette.wikia.nocookie.net/animalcrossing/images/6/6d/NH-Bruce_poster.png
Bubbles,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8d/NH-Bubbles_poster.png
Buck,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b2/NH-Buck_poster.png
Bud,https://vignette.wikia.nocookie.net/animalcrossing/images/a/ab/NH-Bud_poster.png
Bunnie,https://vignette.wikia.nocookie.net/animalcrossing/images/8/83/NH-Bunnie_poster.png
Butch,https://vignette.wikia.nocookie.net/animalcrossing/images/9/9a/NH-Butch_poster.png
Buzz,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f2/NH-Buzz_poster.png
Cally,https://vignette.wikia.nocookie.net/animalcrossing/images/0/01/NH-Cally_poster.png
Camofrog,https://vignette.wikia.nocookie.net/animalcrossing/images/9/91/NH-Camofrog_poster.png
Canberra,https://vignette.wikia.nocookie.net/animalcrossing/images/f/fd/NH-Canberra_poster.png
Candi,https://vignette.wikia.nocookie.net/animalcrossing/images/c/ce/NH-Candi_poster.png
Carmen,https://vignette.wikia.nocookie.net/animalcrossing/images/1/1b/NH-Carmen_poster.png
Caroline,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a5/NH-Caroline_poster.png
Carrie,https://vignette.wikia.nocookie.net/animalcrossing/images/0/0d/NH-Carrie_poster.png
Cashmere,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8a/NH-Cashmere_poster.png
Celia,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8a/NH-Celia_poster.png
Cesar,https://vignette.wikia.nocookie.net/animalcrossing/images/f/fd/NH-Cesar_poster.png
Chadder,https://vignette.wikia.nocookie.net/animalcrossing/images/3/33/NH-Chadder_poster.png
Charlise,https://vignette.wikia.nocookie.net/animalcrossing/images/7/71/NH-Charlise_poster.png
Cheri,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5c/NH-Cheri_poster.png
Cherry,https://vignette.wikia.nocookie.net/animalcrossing/images/6/6e/NH-Cherry_poster.png
Chester,https://vignette.wikia.nocookie.net/animalcrossing/images/c/cf/NH-Chester_poster.png
Chevre,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f4/NH-Chevre_poster.png
Chief,https://vignette.wikia.nocookie.net/animalcrossing/images/5/56/NH-Chief_poster.png
Chops,https://vignette.wikia.nocookie.net/animalcrossing/images/6/6d/NH-Chops_poster.png
Chow,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b7/NH-Chow_poster.png
Chrissy,https://vignette.wikia.nocookie.net/animalcrossing/images/1/1f/NH-Chrissy_poster.png
Claude,https://vignette.wikia.nocookie.net/animalcrossing/images/1/19/NH-Claude_poster.png
Claudia,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b1/NH-Claudia_poster.png
Clay,https://vignette.wikia.nocookie.net/animalcrossing/images/0/0a/NH-Clay_poster.png
Cleo,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5e/NH-Cleo_poster.png
Clyde,https://vignette.wikia.nocookie.net/animalcrossing/images/9/93/NH-Clyde_poster.png
Coach,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a3/NH-Coach_poster.png
Cobb,https://vignette.wikia.nocookie.net/animalcrossing/images/6/6d/NH-Cobb_poster.png
Coco,https://vignette.wikia.nocookie.net/animalcrossing/images/3/37/NH-Coco_poster.png
Cole,https://vignette.wikia.nocookie.net/animalcrossing/images/6/60/NH-Cole_poster.png
Colton,https://vignette.wikia.nocookie.net/animalcrossing/images/0/04/NH-Colton_poster.png
Cookie,https://vignette.wikia.nocookie.net/animalcrossing/images/8/85/NH-Cookie_poster.png
Cousteau,https://vignette.wikia.nocookie.net/animalcrossing/images/4/41/NH-Cousteau_poster.png
Cranston,https://vignette.wikia.nocookie.net/animalcrossing/images/7/75/NH-Cranston_poster.png
Croque,https://vignette.wikia.nocookie.net/animalcrossing/images/9/9a/NH-Croque_poster.png
Cube,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c6/NH-Cube_poster.png
Curlos,https://vignette.wikia.nocookie.net/animalcrossing/images/1/15/NH-Curlos_poster.png
Curly,https://vignette.wikia.nocookie.net/animalcrossing/images/1/14/NH-Curly_poster.png
Curt,https://vignette.wikia.nocookie.net/animalcrossing/images/e/ef/NH-Curt_poster.png
Cyd,https://vignette.wikia.nocookie.net/animalcrossing/images/9/9b/NH-Cyd_poster.png
Cyrano,https://vignette.wikia.nocookie.net/animalcrossing/images/6/65/NH-Cyrano_poster.png
Daisy,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a8/NH-Daisy_poster.png
Deena,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f5/NH-Deena_poster.png
Deirdre,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c0/NH-Deirdre_poster.png
Del,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c2/NH-Del_poster.png
Deli,https://vignette.wikia.nocookie.net/animalcrossing/images/0/03/NH-Deli_poster.png
Derwin,https://vignette.wikia.nocookie.net/animalcrossing/images/9/95/NH-Derwin_poster.png
Diana,https://vignette.wikia.nocookie.net/animalcrossing/images/1/10/NH-Diana_poster.png
Diva,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e7/NH-Diva_poster.png
Dizzy,https://vignette.wikia.nocookie.net/animalcrossing/images/6/65/NH-Dizzy_poster.png
Dobie,https://vignette.wikia.nocookie.net/animalcrossing/images/9/90/NH-Dobie_poster.png
Doc,https://vignette.wikia.nocookie.net/animalcrossing/images/5/52/NH-Doc_poster.png
Dom,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b2/NH-Dom_poster.png
Dora,https://vignette.wikia.nocookie.net/animalcrossing/images/e/ed/NH-Dora_poster.png
Dotty,https://vignette.wikia.nocookie.net/animalcrossing/images/7/72/NH-Dotty_poster.png
Drago,https://vignette.wikia.nocookie.net/animalcrossing/images/5/52/NH-Drago_poster.png
Drake,https://vignette.wikia.nocookie.net/animalcrossing/images/1/16/NH-Drake_poster.png
Drift,https://vignette.wikia.nocookie.net/animalcrossing/images/7/7f/NH-Drift_poster.png
Ed,https://vignette.wikia.nocookie.net/animalcrossing/images/2/20/NH-Ed_poster.png
Egbert,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d8/NH-Egbert_poster.png
Elise,https://vignette.wikia.nocookie.net/animalcrossing/images/c/cf/NH-Elise_poster.png
Ellie,https://vignette.wikia.nocookie.net/animalcrossing/images/1/12/NH-Ellie_poster.png
Elmer,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a5/NH-Elmer_poster.png
Eloise,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d1/NH-Eloise_poster.png
Elvis,https://vignette.wikia.nocookie.net/animalcrossing/images/3/36/NH-Elvis_poster.png
Erik,https://vignette.wikia.nocookie.net/animalcrossing/images/f/fc/NH-Erik_poster.png
Eunice,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a4/NH-Eunice_poster.png
Eugene,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f7/NH-Eugene_poster.png
Fang,https://vignette.wikia.nocookie.net/animalcrossing/images/7/77/NH-Fang_poster.png
Fauna,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b4/NH-Fauna_poster.png
Felicity,https://vignette.wikia.nocookie.net/animalcrossing/images/8/80/NH-Felicity_poster.png
Filbert,https://vignette.wikia.nocookie.net/animalcrossing/images/3/3e/NH-Filbert_poster.png
Flip,https://vignette.wikia.nocookie.net/animalcrossing/images/1/19/NH-Flip_poster.png
Flo,https://vignette.wikia.nocookie.net/animalcrossing/images/9/97/NH-Flo_poster.png
Flora,https://vignette.wikia.nocookie.net/animalcrossing/images/4/46/NH-Flora_poster.png
Flurry,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a3/NH-Flurry_poster.png
Francine,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a1/NH-Francine_poster.png
Frank,https://vignette.wikia.nocookie.net/animalcrossing/images/8/86/NH-Frank_poster.png
Freckles,https://vignette.wikia.nocookie.net/animalcrossing/images/e/ea/NH-Freckles_poster.png
Freya,https://vignette.wikia.nocookie.net/animalcrossing/images/1/19/NH-Freya_poster.png
Friga,https://vignette.wikia.nocookie.net/animalcrossing/images/7/75/NH-Friga_poster.png
Frita,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5e/NH-Frita_poster.png
Frobert,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5a/NH-Frobert_poster.png
Fuchsia,https://vignette.wikia.nocookie.net/animalcrossing/images/b/bf/NH-Fuchsia_poster.png
Gabi,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8b/NH-Gabi_poster.png
Gala,https://vignette.wikia.nocookie.net/animalcrossing/images/8/87/NH-Gala_poster.png
Gaston,https://vignette.wikia.nocookie.net/animalcrossing/images/6/6f/NH-Gaston_poster.png
Gayle,https://vignette.wikia.nocookie.net/animalcrossing/images/e/ee/NH-Gayle_poster.png
Genji,https://vignette.wikia.nocookie.net/animalcrossing/images/7/70/NH-Genji_poster.png
Gigi,https://vignette.wikia.nocookie.net/animalcrossing/images/4/44/NH-Gigi_poster.png
Gladys,https://vignette.wikia.nocookie.net/animalcrossing/images/6/65/NH-Gladys_poster.png
Gloria,https://vignette.wikia.nocookie.net/animalcrossing/images/4/4d/NH-Gloria_poster.png
Goldie,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e6/NH-Goldie_poster.png
Gonzo,https://vignette.wikia.nocookie.net/animalcrossing/images/d/de/NH-Gonzo_poster.png
Goose,https://vignette.wikia.nocookie.net/animalcrossing/images/a/ab/NH-Goose_poster.png
Graham,https://vignette.wikia.nocookie.net/animalcrossing/images/c/cf/NH-Graham_poster.png
Greta,https://vignette.wikia.nocookie.net/animalcrossing/images/1/1c/NH-Greta_poster.png
Grizzly,https://vignette.wikia.nocookie.net/animalcrossing/images/9/96/NH-Grizzly_poster.png
Groucho,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f7/NH-Groucho_poster.png
Gruff,https://vignette.wikia.nocookie.net/animalcrossing/images/4/44/NH-Gruff_poster.png
Gwen,https://vignette.wikia.nocookie.net/animalcrossing/images/0/04/NH-Gwen_poster.png
Hamlet,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b2/NH-Hamlet_poster.png
Hamphrey,https://vignette.wikia.nocookie.net/animalcrossing/images/5/56/NH-Hamphrey_poster.png
Hans,https://vignette.wikia.nocookie.net/animalcrossing/images/e/eb/NH-Hans_poster.png
Harry,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8d/NH-Harry_poster.png
Hazel,https://vignette.wikia.nocookie.net/animalcrossing/images/4/48/NH-Hazel_poster.png
Henry,https://vignette.wikia.nocookie.net/animalcrossing/images/2/24/NH-Henry_poster.png
Hippeux,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a3/NH-Hippeux_poster.png
Hopkins,https://vignette.wikia.nocookie.net/animalcrossing/images/0/00/NH-Hopkins_poster.png
Hopper,https://vignette.wikia.nocookie.net/animalcrossing/images/0/01/NH-Hopper_poster.png
Hornsby,https://vignette.wikia.nocookie.net/animalcrossing/images/4/48/NH-Hornsby_poster.png
Huck,https://vignette.wikia.nocookie.net/animalcrossing/images/b/ba/NH-Huck_poster.png
Hugh,https://vignette.wikia.nocookie.net/animalcrossing/images/3/3e/NH-Hugh_poster.png
Iggly,https://vignette.wikia.nocookie.net/animalcrossing/images/4/48/NH-Iggly_poster.png
Ike,https://vignette.wikia.nocookie.net/animalcrossing/images/3/33/NH-Ike_poster.png
JacobNAJakeyPAL,https://vignette.wikia.nocookie.net/animalcrossing/images/6/65/NH-Jacob_poster.png
Jacques,https://vignette.wikia.nocookie.net/animalcrossing/images/b/bf/NH-Jacques_poster.png
Jambette,https://vignette.wikia.nocookie.net/animalcrossing/images/a/ab/NH-Jambette_poster.png
Jay,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e6/NH-Jay_poster.png
Jeremiah,https://vignette.wikia.nocookie.net/animalcrossing/images/c/cd/NH-Jeremiah_poster.png
Jitters,https://vignette.wikia.nocookie.net/animalcrossing/images/d/de/NH-Jitters_poster.png
Joey,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e4/NH-Joey_poster.png
Judy,https://vignette.wikia.nocookie.net/animalcrossing/images/5/50/NH-Judy_poster.png
Julia,https://vignette.wikia.nocookie.net/animalcrossing/images/f/fc/NH-Julia_poster.png
Julian,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f4/NH-Julian_poster.png
June,https://vignette.wikia.nocookie.net/animalcrossing/images/9/90/NH-June_poster.png
Kabuki,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f1/NH-Kabuki_poster.png
Katt,https://vignette.wikia.nocookie.net/animalcrossing/images/e/ee/NH-Katt_poster.png
Keaton,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e5/NH-Keaton_poster.png
Ken,https://vignette.wikia.nocookie.net/animalcrossing/images/2/2d/NH-Ken_poster.png
Ketchup,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e1/NH-Ketchup_poster.png
Kevin,https://vignette.wikia.nocookie.net/animalcrossing/images/2/20/NH-Kevin_poster.png
Kid Cat,https://vignette.wikia.nocookie.net/animalcrossing/images/3/30/NH-Kid_Cat_poster.png
Kidd,https://vignette.wikia.nocookie.net/animalcrossing/images/4/46/NH-Kidd_poster.png
Kiki,https://vignette.wikia.nocookie.net/animalcrossing/images/3/34/NH-Kiki_poster.png
Kitt,https://vignette.wikia.nocookie.net/animalcrossing/images/e/ed/NH-Kitt_poster.png
Kitty,https://vignette.wikia.nocookie.net/animalcrossing/images/7/7a/NH-Kitty_poster.png
Klaus,https://vignette.wikia.nocookie.net/animalcrossing/images/5/56/NH-Klaus_poster.png
Knox,https://vignette.wikia.nocookie.net/animalcrossing/images/4/45/NH-Knox_poster.png
Kody,https://vignette.wikia.nocookie.net/animalcrossing/images/3/30/NH-Kody_poster.png
Kyle,https://vignette.wikia.nocookie.net/animalcrossing/images/9/93/NH-Kyle_poster.png
Leonardo,https://vignette.wikia.nocookie.net/animalcrossing/images/1/1a/NH-Leonardo_poster.png
Leopold,https://vignette.wikia.nocookie.net/animalcrossing/images/d/dc/NH-Leopold_poster.png
Lily,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f0/NH-Lily_poster.png
Limberg,https://vignette.wikia.nocookie.net/animalcrossing/images/1/12/NH-Limberg_poster.png
Lionel,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b1/NH-Lionel_poster.png
Lobo,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f8/NH-Lobo_poster.png
Lolly,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b0/NH-Lolly_poster.png
Lopez,https://vignette.wikia.nocookie.net/animalcrossing/images/d/dc/NH-Lopez_poster.png
Louie,https://vignette.wikia.nocookie.net/animalcrossing/images/1/13/NH-Louie_poster.png
Lucha,https://vignette.wikia.nocookie.net/animalcrossing/images/d/dc/NH-Lucha_poster.png
Lucky,https://vignette.wikia.nocookie.net/animalcrossing/images/4/4d/NH-Lucky_poster.png
Lucy,https://vignette.wikia.nocookie.net/animalcrossing/images/1/14/NH-Lucy_poster.png
Lyman,https://vignette.wikia.nocookie.net/animalcrossing/images/1/1a/NH-Lyman_poster.png
Mac,https://vignette.wikia.nocookie.net/animalcrossing/images/4/4d/NH-Mac_poster.png
Maddie,https://vignette.wikia.nocookie.net/animalcrossing/images/0/07/NH-Maddie_poster.png
Maelle,https://vignette.wikia.nocookie.net/animalcrossing/images/d/de/NH-Maelle_poster.png
Maggie,https://vignette.wikia.nocookie.net/animalcrossing/images/4/4f/NH-Maggie_poster.png
Mallary,https://vignette.wikia.nocookie.net/animalcrossing/images/3/35/NH-Mallary_poster.png
Maple,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d1/NH-Maple_poster.png
Marcel,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e5/NH-Marcel_poster.png
Marcie,https://vignette.wikia.nocookie.net/animalcrossing/images/d/db/NH-Marcie_poster.png
Margie,https://vignette.wikia.nocookie.net/animalcrossing/images/f/ff/NH-Margie_poster.png
Marina,https://vignette.wikia.nocookie.net/animalcrossing/images/f/fd/NH-Marina_poster.png
Marshal,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e6/NH-Marshal_poster.png
Mathilda,https://vignette.wikia.nocookie.net/animalcrossing/images/8/81/NH-Mathilda_poster.png
Megan,https://vignette.wikia.nocookie.net/animalcrossing/images/1/18/NH-Megan_poster.png
Melba,https://vignette.wikia.nocookie.net/animalcrossing/images/5/57/NH-Melba_poster.png
Merengue,https://vignette.wikia.nocookie.net/animalcrossing/images/9/9d/NH-Merengue_poster.png
Merry,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f0/NH-Merry_poster.png
Midge,https://vignette.wikia.nocookie.net/animalcrossing/images/8/86/NH-Midge_poster.png
Mint,https://vignette.wikia.nocookie.net/animalcrossing/images/2/2a/NH-Mint_poster.png
Mira,https://vignette.wikia.nocookie.net/animalcrossing/images/7/79/NH-Mira_poster.png
Miranda,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f4/NH-Miranda_poster.png
Mitzi,https://vignette.wikia.nocookie.net/animalcrossing/images/2/20/NH-Mitzi_poster.png
Moe,https://vignette.wikia.nocookie.net/animalcrossing/images/7/7e/NH-Moe_poster.png
Molly,https://vignette.wikia.nocookie.net/animalcrossing/images/0/00/NH-Molly_poster.png
Monique,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d3/NH-Monique_poster.png
Monty,https://vignette.wikia.nocookie.net/animalcrossing/images/2/2b/NH-Monty_poster.png
Moose,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b2/NH-Moose_poster.png
Mott,https://vignette.wikia.nocookie.net/animalcrossing/images/6/66/NH-Mott_poster.png
Muffy,https://vignette.wikia.nocookie.net/animalcrossing/images/7/70/NH-Muffy_poster.png
Murphy,https://vignette.wikia.nocookie.net/animalcrossing/images/6/69/NH-Murphy_poster.png
Nan,https://vignette.wikia.nocookie.net/animalcrossing/images/d/de/NH-Nan_poster.png
Nana,https://vignette.wikia.nocookie.net/animalcrossing/images/6/64/NH-Nana_poster.png
Naomi,https://vignette.wikia.nocookie.net/animalcrossing/images/9/97/NH-Naomi_poster.png
Nate,https://vignette.wikia.nocookie.net/animalcrossing/images/1/1a/NH-Nate_poster.png
Nibbles,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d5/NH-Nibbles_poster.png
Norma,https://vignette.wikia.nocookie.net/animalcrossing/images/9/94/NH-Norma_poster.png
Octavian,https://vignette.wikia.nocookie.net/animalcrossing/images/8/82/NH-Octavian_poster.png
O'Hare,https://vignette.wikia.nocookie.net/animalcrossing/images/5/57/NH-O%27Hare_poster.png
Olaf,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5c/NH-Olaf_poster.png
Olive,https://vignette.wikia.nocookie.net/animalcrossing/images/f/fd/NH-Olive_poster.png
Olivia,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5a/NH-Olivia_poster.png
Opal,https://vignette.wikia.nocookie.net/animalcrossing/images/7/73/NH-Opal_poster.png
Ozzie,https://vignette.wikia.nocookie.net/animalcrossing/images/2/2c/NH-Ozzie_poster.png
Pancetti,https://vignette.wikia.nocookie.net/animalcrossing/images/4/49/NH-Pancetti_poster.png
Pango,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d3/NH-Pango_poster.png
Paolo,https://vignette.wikia.nocookie.net/animalcrossing/images/f/fc/NH-Paolo_poster.png
Papi,https://vignette.wikia.nocookie.net/animalcrossing/images/6/6d/NH-Papi_poster.png
Pashmina,https://vignette.wikia.nocookie.net/animalcrossing/images/2/29/NH-Pashmina_poster.png
Pate,https://vignette.wikia.nocookie.net/animalcrossing/images/2/20/NH-Pate_poster.png
Patty,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f8/NH-Patty_poster.png
Paula,https://vignette.wikia.nocookie.net/animalcrossing/images/7/79/NH-Paula_poster.png
Peaches,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8a/NH-Peaches_poster.png
Peanut,https://vignette.wikia.nocookie.net/animalcrossing/images/6/68/NH-Peanut_poster.png
Pecan,https://vignette.wikia.nocookie.net/animalcrossing/images/4/48/NH-Pecan_poster.png
Peck,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d8/NH-Peck_poster.png
Peewee,https://vignette.wikia.nocookie.net/animalcrossing/images/c/cb/NH-Peewee_poster.png
Peggy,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a1/NH-Peggy_poster.png
Pekoe,https://vignette.wikia.nocookie.net/animalcrossing/images/6/6a/NH-Pekoe_poster.png
Penelope,https://vignette.wikia.nocookie.net/animalcrossing/images/7/72/NH-Penelope_poster.png
Phil,https://vignette.wikia.nocookie.net/animalcrossing/images/2/26/NH-Phil_poster.png
Phoebe,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8b/NH-Phoebe_poster.png
Pierce,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8f/NH-Pierce_poster.png
Pietro,https://vignette.wikia.nocookie.net/animalcrossing/images/2/21/NH-Pietro_poster.png
Pinky,https://vignette.wikia.nocookie.net/animalcrossing/images/e/ea/NH-Pinky_poster.png
Piper,https://vignette.wikia.nocookie.net/animalcrossing/images/4/47/NH-Piper_poster.png
Pippy,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8c/NH-Pippy_poster.png
Plucky,https://vignette.wikia.nocookie.net/animalcrossing/images/6/62/NH-Plucky_poster.png
Pompom,https://vignette.wikia.nocookie.net/animalcrossing/images/1/18/NH-Pompom_poster.png
Poncho,https://vignette.wikia.nocookie.net/animalcrossing/images/e/ea/NH-Poncho_poster.png
Poppy,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5c/NH-Poppy_poster.png
Portia,https://vignette.wikia.nocookie.net/animalcrossing/images/7/79/NH-Portia_poster.png
Prince,https://vignette.wikia.nocookie.net/animalcrossing/images/0/0b/NH-Prince_poster.png
Puck,https://vignette.wikia.nocookie.net/animalcrossing/images/5/52/NH-Puck_poster.png
Puddles,https://vignette.wikia.nocookie.net/animalcrossing/images/7/78/NH-Puddles_poster.png
Pudge,https://vignette.wikia.nocookie.net/animalcrossing/images/2/2b/NH-Pudge_poster.png
Punchy,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d2/NH-Punchy_poster.png
Purrl,https://vignette.wikia.nocookie.net/animalcrossing/images/3/3d/NH-Purrl_poster.png
Queenie,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c6/NH-Queenie_poster.png
Quillson,https://vignette.wikia.nocookie.net/animalcrossing/images/6/69/NH-Quillson_poster.png
Raddle,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5b/NH-Raddle_poster.png
Rasher,https://vignette.wikia.nocookie.net/animalcrossing/images/b/ba/NH-Rasher_poster.png
Raymond,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8e/NH-Raymond_poster.png
Renée,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d8/NH-Ren%C3%A9e_poster.png
Reneigh,https://vignette.wikia.nocookie.net/animalcrossing/images/3/33/NH-Reneigh_poster.png
Rex,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a7/NH-Rex_poster.png
Rhonda,https://vignette.wikia.nocookie.net/animalcrossing/images/1/12/NH-Rhonda_poster.png
Ribbot,https://vignette.wikia.nocookie.net/animalcrossing/images/4/4e/NH-Ribbot_poster.png
Ricky,https://vignette.wikia.nocookie.net/animalcrossing/images/6/6b/NH-Ricky_poster.png
Rizzo,https://vignette.wikia.nocookie.net/animalcrossing/images/9/93/NH-Rizzo_poster.png
Roald,https://vignette.wikia.nocookie.net/animalcrossing/images/4/4f/NH-Roald_poster.png
Robin,https://vignette.wikia.nocookie.net/animalcrossing/images/6/62/NH-Robin_poster.png
Rocco,https://vignette.wikia.nocookie.net/animalcrossing/images/3/32/NH-Rocco_poster.png
Rocket,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d3/NH-Rocket_poster.png
Rod,https://vignette.wikia.nocookie.net/animalcrossing/images/1/10/NH-Rod_poster.png
Rodeo,https://vignette.wikia.nocookie.net/animalcrossing/images/1/15/NH-Rodeo_poster.png
Rodney,https://vignette.wikia.nocookie.net/animalcrossing/images/5/58/NH-Rodney_poster.png
Rolf,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5c/NH-Rolf_poster.png
Rooney,https://vignette.wikia.nocookie.net/animalcrossing/images/3/36/NH-Rooney_poster.png
Rory,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f3/NH-Rory_poster.png
Roscoe,https://vignette.wikia.nocookie.net/animalcrossing/images/0/01/NH-Roscoe_poster.png
Rosie,https://vignette.wikia.nocookie.net/animalcrossing/images/4/46/NH-Rosie_poster.png
Rowan,https://vignette.wikia.nocookie.net/animalcrossing/images/4/41/NH-Rowan_poster.png
Ruby,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5c/NH-Ruby_poster.png
Rudy,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c1/NH-Rudy_poster.png
Sally,https://vignette.wikia.nocookie.net/animalcrossing/images/5/5d/NH-Sally_poster.png
Samson,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d7/NH-Samson_poster.png
Sandy,https://vignette.wikia.nocookie.net/animalcrossing/images/9/93/NH-Sandy_poster.png
Savannah,https://vignette.wikia.nocookie.net/animalcrossing/images/1/10/NH-Savannah_poster.png
Scoot,https://vignette.wikia.nocookie.net/animalcrossing/images/9/9d/NH-Scoot_poster.png
Shari,https://vignette.wikia.nocookie.net/animalcrossing/images/4/47/NH-Shari_poster.png
Sheldon,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8e/NH-Sheldon_poster.png
Shep,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e9/NH-Shep_poster.png
Sherb,https://vignette.wikia.nocookie.net/animalcrossing/images/0/04/Sherb_Poster_NH.png
Simon,https://vignette.wikia.nocookie.net/animalcrossing/images/6/6a/NH-Simon_poster.png
Skye,https://vignette.wikia.nocookie.net/animalcrossing/images/1/10/NH-Skye_poster.png
Sly,https://vignette.wikia.nocookie.net/animalcrossing/images/7/7f/NH-Sly_poster.png
Snake,https://vignette.wikia.nocookie.net/animalcrossing/images/2/2c/NH-Snake_poster.png
Snooty,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d2/NH-Snooty_poster.png
Soleil,https://vignette.wikia.nocookie.net/animalcrossing/images/9/9f/NH-Soleil_poster.png
Sparro,https://vignette.wikia.nocookie.net/animalcrossing/images/6/69/NH-Sparro_poster.png
Spike,https://vignette.wikia.nocookie.net/animalcrossing/images/9/95/NH-Spike_poster.png
SporkNACracklePAL,https://vignette.wikia.nocookie.net/animalcrossing/images/d/db/NH-Spork_poster.png
Sprinkle,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e5/NH-Sprinkle_poster.png
Sprocket,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e6/NH-Sprocket_poster.png
Static,https://vignette.wikia.nocookie.net/animalcrossing/images/f/ff/NH-Static_poster.png
Stella,https://vignette.wikia.nocookie.net/animalcrossing/images/5/50/NH-Stella_poster.png
Sterling,https://vignette.wikia.nocookie.net/animalcrossing/images/0/0a/NH-Sterling_poster.png
Stinky,https://vignette.wikia.nocookie.net/animalcrossing/images/c/cc/NH-Stinky_poster.png
Stitches,https://vignette.wikia.nocookie.net/animalcrossing/images/0/0a/NH-Stitches_poster.png
Stu,https://vignette.wikia.nocookie.net/animalcrossing/images/f/fc/NH-Stu_poster.png
Sydney,https://vignette.wikia.nocookie.net/animalcrossing/images/f/f6/NH-Sydney_poster.png
Sylvana,https://vignette.wikia.nocookie.net/animalcrossing/images/4/41/NH-Sylvana_poster.png
Sylvia,https://vignette.wikia.nocookie.net/animalcrossing/images/4/4b/NH-Sylvia_poster.png
Tabby,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d7/NH-Tabby_poster.png
Tad,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c8/NH-Tad_poster.png
Tammi,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d1/NH-Tammi_poster.png
Tammy,https://vignette.wikia.nocookie.net/animalcrossing/images/6/66/NH-Tammy_poster.png
Tangy,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c8/NH-Tangy_poster.png
Tank,https://vignette.wikia.nocookie.net/animalcrossing/images/e/eb/NH-Tank_poster.png
Tasha,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d3/NH-Tasha_poster.png
T-Bone,https://vignette.wikia.nocookie.net/animalcrossing/images/c/ca/NH-T-Bone_poster.png
Teddy,https://vignette.wikia.nocookie.net/animalcrossing/images/1/11/NH-Teddy_poster.png
Tex,https://vignette.wikia.nocookie.net/animalcrossing/images/a/a1/NH-Tex_poster.png
Tia,https://vignette.wikia.nocookie.net/animalcrossing/images/4/41/NH-Tia_poster.png
Tiffany,https://vignette.wikia.nocookie.net/animalcrossing/images/f/fb/NH-Tiffany_poster.png
Timbra,https://vignette.wikia.nocookie.net/animalcrossing/images/6/6a/NH-Timbra_poster.png
Tipper,https://vignette.wikia.nocookie.net/animalcrossing/images/6/64/NH-Tipper_poster.png
Tom,https://vignette.wikia.nocookie.net/animalcrossing/images/7/7d/NH-Tom_poster.png
Truffles,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c9/NH-Truffles_poster.png
Tucker,https://vignette.wikia.nocookie.net/animalcrossing/images/3/32/NH-Tucker_poster.png
Tutu,https://vignette.wikia.nocookie.net/animalcrossing/images/9/95/NH-Tutu_poster.png
Twiggy,https://vignette.wikia.nocookie.net/animalcrossing/images/5/52/NH-Twiggy_poster.png
Tybalt,https://vignette.wikia.nocookie.net/animalcrossing/images/d/dc/NH-Tybalt_poster.png
Ursala,https://vignette.wikia.nocookie.net/animalcrossing/images/2/23/NH-Ursala_poster.png
Velma,https://vignette.wikia.nocookie.net/animalcrossing/images/1/17/NH-Velma_poster.png
Vesta,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8f/NH-Vesta_poster.png
Vic,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b9/NH-Vic_poster.png
Victoria,https://vignette.wikia.nocookie.net/animalcrossing/images/4/46/NH-Victoria_poster.png
Violet,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b7/NH-Violet_poster.png
Vivian,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d2/NH-Vivian_poster.png
Vladimir,https://vignette.wikia.nocookie.net/animalcrossing/images/7/7c/NH-Vladimir_poster.png
Wade,https://vignette.wikia.nocookie.net/animalcrossing/images/8/8e/NH-Wade_poster.png
Walker,https://vignette.wikia.nocookie.net/animalcrossing/images/e/e0/NH-Walker_poster.png
Walt,https://vignette.wikia.nocookie.net/animalcrossing/images/3/3a/NH-Walt_poster.png
Wart Jr.,https://vignette.wikia.nocookie.net/animalcrossing/images/d/d7/NH-WartJr_poster.png
Weber,https://vignette.wikia.nocookie.net/animalcrossing/images/5/54/NH-Weber_poster.png
Wendy,https://vignette.wikia.nocookie.net/animalcrossing/images/4/4e/NH-Wendy_poster.png
Whitney,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b0/NH-Whitney_poster.png
Willow,https://vignette.wikia.nocookie.net/animalcrossing/images/0/05/NH-Willow_poster.png
Winnie,https://vignette.wikia.nocookie.net/animalcrossing/images/7/76/NH-Winnie_poster.png
Wolfgang,https://vignette.wikia.nocookie.net/animalcrossing/images/1/19/NH-Wolfgang_poster.png
Yuka,https://vignette.wikia.nocookie.net/animalcrossing/images/b/b6/NH-Yuka_poster.png
Zell,https://vignette.wikia.nocookie.net/animalcrossing/images/c/c8/NH-Zell_poster.png
Zucker,https://vignette.wikia.nocookie.net/animalcrossing/images/1/10/NH-Zucker_poster.png`
.split('\n').map(a => a.split(','));
