const allPokemonNames = Object.freeze([
  "Abomasnow: Mega",
  "Abomasnow",
  "Abra",
  "Absol: Mega",
  "Absol",
  "Accelgor",
  "Aegislash: Blade",
  "Aegislash: Shield",
  "Aerodactyl: Mega",
  "Aerodactyl",
  "Aggron: Mega",
  "Aggron",
  "Aipom",
  "Alakazam: Mega",
  "Alakazam",
  "Alomomola",
  "Altaria: Mega",
  "Altaria",
  "Amaura",
  "Ambipom",
  "Amoonguss",
  "Ampharos: Mega",
  "Ampharos",
  "Anorith",
  "Araquanid",
  "Arbok",
  "Arcanine",
  "Arceus",
  "Archen",
  "Archeops",
  "Ariados",
  "Armaldo",
  "Aromatisse",
  "Aron",
  "Articuno",
  "Audino: Mega",
  "Audino",
  "Aurorus",
  "Avalugg",
  "Axew",
  "Azelf",
  "Azumarill",
  "Azurill",
  "Bagon",
  "Baltoy",
  "Banette: Mega",
  "Banette",
  "Barbaracle",
  "Barboach",
  "Basculin: Blue striped",
  "Basculin: Red striped",
  "Bastiodon",
  "Bayleef",
  "Beartic",
  "Beautifly",
  "Beedrill: Mega",
  "Beedrill",
  "Beheeyem",
  "Beldum",
  "Bellossom",
  "Bellsprout",
  "Bergmite",
  "Bewear",
  "Bibarel",
  "Bidoof",
  "Binacle",
  "Bisharp",
  "Blastoise: Mega",
  "Blastoise",
  "Blaziken: Mega",
  "Blaziken",
  "Blissey",
  "Blitzle",
  "Boldore",
  "Bonsly",
  "Bouffalant",
  "Bounsweet",
  "Braixen",
  "Braviary",
  "Breloom",
  "Brionne",
  "Bronzong",
  "Bronzor",
  "Bruxish",
  "Budew",
  "Buizel",
  "Bulbasaur",
  "Buneary",
  "Bunnelby",
  "Burmy",
  "Butterfree",
  "Buzzwole",
  "Cacnea",
  "Cacturne",
  "Camerupt: Mega",
  "Camerupt",
  "Carbink",
  "Carnivine",
  "Carracosta",
  "Carvanha",
  "Cascoon",
  "Castform: Rainy",
  "Castform: Snowy",
  "Castform: Sunny",
  "Castform",
  "Caterpie",
  "Celebi",
  "Celesteela",
  "Chandelure",
  "Chansey",
  "Charizard: Mega x",
  "Charizard: Mega y",
  "Charizard",
  "Charjabug",
  "Charmander",
  "Charmeleon",
  "Chatot",
  "Cherrim",
  "Cherubi",
  "Chesnaught",
  "Chespin",
  "Chikorita",
  "Chimchar",
  "Chimecho",
  "Chinchou",
  "Chingling",
  "Cinccino",
  "Clamperl",
  "Clauncher",
  "Clawitzer",
  "Claydol",
  "Clefable",
  "Clefairy",
  "Cleffa",
  "Cloyster",
  "Cobalion",
  "Cofagrigus",
  "Combee",
  "Combusken",
  "Comfey",
  "Conkeldurr",
  "Corphish",
  "Corsola",
  "Cosmoem",
  "Cosmog",
  "Cottonee",
  "Crabominable",
  "Crabrawler",
  "Cradily",
  "Cranidos",
  "Crawdaunt",
  "Cresselia",
  "Croagunk",
  "Crobat",
  "Croconaw",
  "Crustle",
  "Cryogonal",
  "Cubchoo",
  "Cubone",
  "Cutiefly",
  "Cyndaquil",
  "Darkrai",
  "Darmanitan",
  "Darmanitan: Zen",
  "Dartrix",
  "Darumaka",
  "Decidueye",
  "Dedenne",
  "Deerling",
  "Deino",
  "Delcatty",
  "Delibird",
  "Delphox",
  "Deoxys",
  "Deoxys: Attack",
  "Deoxys: Defense",
  "Deoxys: Speed",
  "Dewgong",
  "Dewott",
  "Dewpider",
  "Dhelmise",
  "Dialga",
  "Diancie: Mega",
  "Diancie",
  "Diggersby",
  "Diglett",
  "Ditto",
  "Dodrio",
  "Doduo",
  "Donphan",
  "Doublade",
  "Dragalge",
  "Dragonair",
  "Dragonite",
  "Drampa",
  "Drapion",
  "Dratini",
  "Drifblim",
  "Drifloon",
  "Drilbur",
  "Drowzee",
  "Druddigon",
  "Ducklett",
  "Dugtrio",
  "Dunsparce",
  "Duosion",
  "Durant",
  "Dusclops",
  "Dusknoir",
  "Duskull",
  "Dustox",
  "Dwebble",
  "Eelektrik",
  "Eelektross",
  "Eevee",
  "Ekans",
  "Electabuzz",
  "Electivire",
  "Electrike",
  "Electrode",
  "Elekid",
  "Elgyem",
  "Emboar",
  "Emolga",
  "Empoleon",
  "Entei",
  "Escavalier",
  "Espeon",
  "Espurr",
  "Excadrill",
  "Exeggcute",
  "Exeggutor",
  "Exploud",
  "Farfetchd",
  "Fearow",
  "Feebas",
  "Fennekin",
  "Feraligatr",
  "Ferroseed",
  "Ferrothorn",
  "Finneon",
  "Flaaffy",
  "Flabebe",
  "Flareon",
  "Fletchinder",
  "Fletchling",
  "Floatzel",
  "Floette",
  "Floette: Eternal",
  "Florges",
  "Flygon",
  "Fomantis",
  "Foongus",
  "Forretress",
  "Fraxure",
  "Frillish",
  "Froakie",
  "Frogadier",
  "Froslass",
  "Furfrou",
  "Furret",
  "Gabite",
  "Gallade: Mega",
  "Gallade",
  "Galvantula",
  "Garbodor",
  "Garchomp: Mega",
  "Garchomp",
  "Gardevoir: Mega",
  "Gardevoir",
  "Gastly",
  "Gastrodon",
  "Genesect",
  "Gengar: Mega",
  "Gengar",
  "Geodude",
  "Gible",
  "Gigalith",
  "Girafarig",
  "Giratina",
  "Giratina: Altered",
  "Glaceon",
  "Glalie: Mega",
  "Glalie",
  "Glameow",
  "Gligar",
  "Gliscor",
  "Gloom",
  "Gogoat",
  "Golbat",
  "Goldeen",
  "Golduck",
  "Golem",
  "Golett",
  "Golisopod",
  "Golurk",
  "Goodra",
  "Goomy",
  "Gorebyss",
  "Gothita",
  "Gothitelle",
  "Gothorita",
  "Gourgeist",
  "Gourgeist: Large",
  "Gourgeist: Small",
  "Gourgeist: Super",
  "Granbull",
  "Graveler",
  "Greninja",
  "Grimer",
  "Grotle",
  "Groudon: Primal",
  "Groudon",
  "Grovyle",
  "Growlithe",
  "Grubbin",
  "Grumpig",
  "Gulpin",
  "Gumshoos",
  "Gurdurr",
  "Guzzlord",
  "Gyarados: Mega",
  "Gyarados",
  "Hakamo: O",
  "Happiny",
  "Hariyama",
  "Haunter",
  "Hawlucha",
  "Haxorus",
  "Heatmor",
  "Heatran",
  "Heliolisk",
  "Helioptile",
  "Heracross: Mega",
  "Heracross",
  "Herdier",
  "Hippopotas",
  "Hippowdon",
  "Hitmonchan",
  "Hitmonlee",
  "Hitmontop",
  "Ho-oh",
  "Honchkrow",
  "Honedge",
  "Hoopa: Unbound",
  "Hoopa",
  "Hoothoot",
  "Hoppip",
  "Horsea",
  "Houndoom: Mega",
  "Houndoom",
  "Houndour",
  "Huntail",
  "Hydreigon",
  "Hypno",
  "Igglybuff",
  "Illumise",
  "Incineroar",
  "Infernape",
  "Inkay",
  "Ivysaur",
  "Jangmo-o",
  "Jellicent",
  "Jigglypuff",
  "Jirachi",
  "Jolteon",
  "Joltik",
  "Jumpluff",
  "Jynx",
  "Kabuto",
  "Kabutops",
  "Kadabra",
  "Kakuna",
  "Kangaskhan: Mega",
  "Kangaskhan",
  "Karrablast",
  "Kartana",
  "Kecleon",
  "Keldeo",
  "Keldeo: Resolute",
  "Kingdra",
  "Kingler",
  "Kirlia",
  "Klang",
  "Klefki",
  "Klink",
  "Klinklang",
  "Koffing",
  "Komala",
  "Kommo-o",
  "Krabby",
  "Kricketot",
  "Kricketune",
  "Krokorok",
  "Krookodile",
  "Kyogre: Primal",
  "Kyogre",
  "Kyurem: Black",
  "Kyurem: White",
  "Kyurem",
  "Lairon",
  "Lampent",
  "Landorus: Incarnate",
  "Landorus: Therian",
  "Lanturn",
  "Lapras",
  "Larvesta",
  "Larvitar",
  "Latias: Mega",
  "Latias",
  "Latios: Mega",
  "Latios",
  "Leafeon",
  "Leavanny",
  "Ledian",
  "Ledyba",
  "Lickilicky",
  "Lickitung",
  "Liepard",
  "Lileep",
  "Lilligant",
  "Lillipup",
  "Linoone",
  "Litleo",
  "Litten",
  "Litwick",
  "Lombre",
  "Lopunny: Mega",
  "Lopunny",
  "Lotad",
  "Loudred",
  "Lucario: Mega",
  "Lucario",
  "Ludicolo",
  "Lugia",
  "Lumineon",
  "Lunala",
  "Lunatone",
  "Lurantis",
  "Luvdisc",
  "Luxio",
  "Luxray",
  "Lycanroc midday",
  "Machamp",
  "Machoke",
  "Machop",
  "Magby",
  "Magcargo",
  "Magearna",
  "Magikarp",
  "Magmar",
  "Magmortar",
  "Magnemite",
  "Magneton",
  "Magnezone",
  "Makuhita",
  "Malamar",
  "Mamoswine",
  "Manaphy",
  "Mandibuzz",
  "Manectric: Mega",
  "Manectric",
  "Mankey",
  "Mantine",
  "Mantyke",
  "Maractus",
  "Mareanie",
  "Mareep",
  "Marill",
  "Marowak",
  "Marshadow",
  "Marshtomp",
  "Masquerain",
  "Mawile: Mega",
  "Mawile",
  "Medicham: Mega",
  "Medicham",
  "Meditite",
  "Meganium",
  "Meloetta: Aria",
  "Meloetta: Pirouette",
  "Meowstic: Male",
  "Meowstic: Female",
  "Meowth",
  "Mesprit",
  "Metagross: Mega",
  "Metagross",
  "Metang",
  "Metapod",
  "Mew",
  "Mewtwo: Mega x",
  "Mewtwo: Mega y",
  "Mewtwo",
  "Mienfoo",
  "Mienshao",
  "Mightyena",
  "Milotic",
  "Miltank",
  "Mime jr",
  "Mimikyu: Disguised",
  "Minccino",
  "Minior: Red meteor",
  "Minun",
  "Misdreavus",
  "Mismagius",
  "Moltres",
  "Monferno",
  "Morelull",
  "Mothim",
  "Mr-mime",
  "Mudbray",
  "Mudkip",
  "Mudsdale",
  "Muk",
  "Munchlax",
  "Munna",
  "Murkrow",
  "Musharna",
  "Natu",
  "Necrozma",
  "Nidoking",
  "Nidoqueen",
  "Nidoran: Female",
  "Nidoran: Male",
  "Nidorina",
  "Nidorino",
  "Nihilego",
  "Nincada",
  "Ninetales",
  "Ninjask",
  "Noctowl",
  "Noibat",
  "Noivern",
  "Nosepass",
  "Numel",
  "Nuzleaf",
  "Octillery",
  "Oddish",
  "Omanyte",
  "Omastar",
  "Onix",
  "Oranguru",
  "Oricorio: Baile",
  "Oshawott",
  "Pachirisu",
  "Palkia",
  "Palossand",
  "Palpitoad",
  "Pancham",
  "Pangoro",
  "Panpour",
  "Pansage",
  "Pansear",
  "Paras",
  "Parasect",
  "Passimian",
  "Patrat",
  "Pawniard",
  "Pelipper",
  "Persian",
  "Petilil",
  "Phanpy",
  "Phantump",
  "Pheromosa",
  "Phione",
  "Pichu",
  "Pidgeot: Mega",
  "Pidgeot",
  "Pidgeotto",
  "Pidgey",
  "Pidove",
  "Pignite",
  "Pikachu: Belle",
  "Pikachu: Cosplay",
  "Pikachu: Libre",
  "Pikachu: Phd",
  "Pikachu: Pop-star",
  "Pikachu: Rock-star",
  "Pikachu",
  "Pikipek",
  "Piloswine",
  "Pineco",
  "Pinsir: Mega",
  "Pinsir",
  "Piplup",
  "Plusle",
  "Politoed",
  "Poliwag",
  "Poliwhirl",
  "Poliwrath",
  "Ponyta",
  "Poochyena",
  "Popplio",
  "Porygon z",
  "Porygon",
  "Porygon2",
  "Primarina",
  "Primeape",
  "Prinplup",
  "Probopass",
  "Psyduck",
  "Pumpkaboo",
  "Pumpkaboo: Large",
  "Pumpkaboo: Small",
  "Pumpkaboo: Super",
  "Pupitar",
  "Purrloin",
  "Purugly",
  "Pyroar",
  "Pyukumuku",
  "Quagsire",
  "Quilava",
  "Quilladin",
  "Qwilfish",
  "Raichu",
  "Raikou",
  "Ralts",
  "Rampardos",
  "Rapidash",
  "Raticate",
  "Rattata",
  "Rayquaza: Mega",
  "Rayquaza",
  "Regice",
  "Regigigas",
  "Regirock",
  "Registeel",
  "Relicanth",
  "Remoraid",
  "Reshiram",
  "Reuniclus",
  "Rhydon",
  "Rhyhorn",
  "Rhyperior",
  "Ribombee",
  "Riolu",
  "Rockruff",
  "Roggenrola",
  "Roselia",
  "Roserade",
  "Rotom: Fan",
  "Rotom: Frost",
  "Rotom: Heat",
  "Rotom: Mow",
  "Rotom: Wash",
  "Rotom",
  "Rowlet",
  "Rufflet",
  "Sableye: Mega",
  "Sableye",
  "Salamence: Mega",
  "Salamence",
  "Salandit",
  "Salazzle",
  "Samurott",
  "Sandile",
  "Sandshrew",
  "Sandslash",
  "Sandygast",
  "Sawk",
  "Sawsbuck",
  "Scatterbug",
  "Sceptile: Mega",
  "Sceptile",
  "Scizor: Mega",
  "Scizor",
  "Scolipede",
  "Scrafty",
  "Scraggy",
  "Scyther",
  "Seadra",
  "Seaking",
  "Sealeo",
  "Seedot",
  "Seel",
  "Seismitoad",
  "Sentret",
  "Serperior",
  "Servine",
  "Seviper",
  "Sewaddle",
  "Sharpedo: Mega",
  "Sharpedo",
  "Shaymin: Land",
  "Shaymin: Sky",
  "Shedinja",
  "Shelgon",
  "Shellder",
  "Shellos",
  "Shelmet",
  "Shieldon",
  "Shiftry",
  "Shiinotic",
  "Shinx",
  "Shroomish",
  "Shuckle",
  "Shuppet",
  "Sigilyph",
  "Silcoon",
  "Silvally",
  "Simipour",
  "Simisage",
  "Simisear",
  "Skarmory",
  "Skiddo",
  "Skiploom",
  "Skitty",
  "Skorupi",
  "Skrelp",
  "Skuntank",
  "Slaking",
  "Slakoth",
  "Sliggoo",
  "Slowbro: Mega",
  "Slowbro",
  "Slowking",
  "Slowpoke",
  "Slugma",
  "Slurpuff",
  "Smeargle",
  "Smoochum",
  "Sneasel",
  "Snivy",
  "Snorlax",
  "Snorunt",
  "Snover",
  "Snubbull",
  "Solgaleo",
  "Solosis",
  "Solrock",
  "Spearow",
  "Spewpa",
  "Spheal",
  "Spinarak",
  "Spinda",
  "Spiritomb",
  "Spoink",
  "Spritzee",
  "Squirtle",
  "Stantler",
  "Staraptor",
  "Staravia",
  "Starly",
  "Starmie",
  "Staryu",
  "Steelix: Mega",
  "Steelix",
  "Steenee",
  "Stoutland",
  "Stufful",
  "Stunfisk",
  "Stunky",
  "Sudowoodo",
  "Suicune",
  "Sunflora",
  "Sunkern",
  "Surskit",
  "Swablu",
  "Swadloon",
  "Swalot",
  "Swampert: Mega",
  "Swampert",
  "Swanna",
  "Swellow",
  "Swinub",
  "Swirlix",
  "Swoobat",
  "Sylveon",
  "Taillow",
  "Talonflame",
  "Tangela",
  "Tangrowth",
  "Tapu: Bulu",
  "Tapu: Fini",
  "Tapu: Koko",
  "Tapu: Lele",
  "Tauros",
  "Teddiursa",
  "Tentacool",
  "Tentacruel",
  "Tepig",
  "Terrakion",
  "Throh",
  "Thundurus: Incarnate",
  "Thundurus: Therian",
  "Timburr",
  "Tirtouga",
  "Togedemaru",
  "Togekiss",
  "Togepi",
  "Togetic",
  "Torchic",
  "Torkoal",
  "Tornadus: Incarnate",
  "Tornadus: Therian",
  "Torracat",
  "Torterra",
  "Totodile",
  "Toucannon",
  "Toxapex",
  "Toxicroak",
  "Tranquill",
  "Trapinch",
  "Treecko",
  "Trevenant",
  "Tropius",
  "Trubbish",
  "Trumbeak",
  "Tsareena",
  "Turtonator",
  "Turtwig",
  "Tympole",
  "Tynamo",
  "Type: Null",
  "Typhlosion",
  "Tyranitar: Mega",
  "Tyranitar",
  "Tyrantrum",
  "Tyrogue",
  "Tyrunt",
  "Umbreon",
  "Unfezant",
  "Unown",
  "Ursaring",
  "Uxie",
  "Vanillish",
  "Vanillite",
  "Vanilluxe",
  "Vaporeon",
  "Venipede",
  "Venomoth",
  "Venonat",
  "Venusaur: Mega",
  "Venusaur",
  "Vespiquen",
  "Vibrava",
  "Victini",
  "Victreebel",
  "Vigoroth",
  "Vikavolt",
  "Vileplume",
  "Virizion",
  "Vivillon",
  "Volbeat",
  "Volcanion",
  "Volcarona",
  "Voltorb",
  "Vullaby",
  "Vulpix",
  "Wailmer",
  "Wailord",
  "Walrein",
  "Wartortle",
  "Watchog",
  "Weavile",
  "Weedle",
  "Weepinbell",
  "Weezing",
  "Whimsicott",
  "Whirlipede",
  "Whiscash",
  "Whismur",
  "Wigglytuff",
  "Wimpod",
  "Wingull",
  "Wishiwashi: Solo",
  "Wobbuffet",
  "Woobat",
  "Wooper",
  "Wormadam: Plant",
  "Wormadam: Sandy",
  "Wormadam: Trash",
  "Wurmple",
  "Wynaut",
  "Xatu",
  "Xerneas",
  "Xurkitree",
  "Yamask",
  "Yanma",
  "Yanmega",
  "Yungoos",
  "Yveltal",
  "Zangoose",
  "Zapdos",
  "Zebstrika",
  "Zekrom",
  "Zigzagoon",
  "Zoroark",
  "Zorua",
  "Zubat",
  "Zweilous",
  "Zygarde",
]);

export default allPokemonNames;
