var defaultGirls = [
  "Akanksha",
  "Alicia",
  "Anika",
  "Brianne",
  "Cassy",
  "Chachi",
  "Camille",
  "Danya",
  "Emily",
  "Ezra",
  "Ezzati",
  "Gabrielle",
  "Grace",
  "Illia",
  "Irene",
  "Jesse",
  "Jessica",
  "Jing Mei",
  "Joyce",
  "Julietta",
  "Kai Lin",
  "Karen",
  "Katherine",
  "Katrina",
  "Kyle",
  "Maria",
  "Maryann",
  "Melissa",
  "Merdin",
  "Naning",
  "Nathalie",
  "Nazish",
  "Neeta",
  "Rose",
  "Sarah",
  "Sareena",
  "Shefali",
  "Sherly",
  "Tanaya",
  "Vanessa",
  "Varsha",
  "Yimin",
  "Yvonne",

  "Chun-Li",
  "The Queen",
  "Cleopatra",

  "$person's gran",
  "$person's wife",
  "$person's pet $object"
];

var defaultBoys = [
  "Abdulla",
  "Abhilash",
  "Adam",
  "Akul",
  "Alberto",
  "Alex",
  "Artan",
  "Arthur",
  "Bill",
  "Bradley",
  "Brook",
  "Bruce",
  "Cameron",
  "Carlito",
  "Craig",
  "Danny",
  "Dilip",
  "Evgeny",
  "Frankie",
  "Gherry",
  "Gurpal",
  "Harris",
  "Jason",
  "Joe",
  "John",
  "Jordan",
  "Justin",
  "Keith",
  "Khaliq",
  "Lachlan",
  "Le Vady",
  "Levady",
  "Lucas",
  "Mark",
  "Martin",
  "Matt",
  "Matthew",
  "Max",
  "Michael",
  "Mitch",
  "Mohammad",
  "Muhd",
  "Oscar",
  "Phil",
  "Philip",
  "Ravinder",
  "Rencheng",
  "Richard",
  "Rizwan",
  "Ro",
  "Rudolph",
  "Santa",
  "Seb",
  "Sebastien",
  "Selva",
  "Shekhar",
  "Stephen",
  "Sunny",
  "Yi-Wei",
  "Yuri",

  "Moko",
  "Jesus",
  "Yoda",

  "$person's grandpapa",
  "$person's husband",
  "$person's dirty uncle",
  "$person's favourite $object"
];

var defaultPrefixes = [
  " unfortunately",
  " likely",
  " briefly",
  " suddenly",
  " actually",
  " literally",
  ", like,",
  " really",
  " just",
  " recently",
  " drunkenly",
  " TOTALLY",
  " painfully",
  ", without a second thought,"
];

var defaultObjects = [
  "$themself",
  "$their lightsabre",
  "you",
  "nothing",
  "$their dad",
  "$person's mum",
  "$adj man",
  "$adj woman",
  "that... that <em>thing</em>",
  "some poop",
  "an air guitar",
  "some fat",
  "$their dog",
  "a pen",
  "$adj goblin",
  "$adj penguin",
  "$adj monkey",
  "$their tongue",
  "a napkin",
  "$their face",
  "a GIANT octopus",
  "Cthulu"
];

var defaultPlaces = [
  "at the big game",
  "down the stairs",
  "in a coffin",
  "over the moon",
  "for $subject",
  "in place",
  "instead of $person",
  "in the bathroom",
  "followed by $object",
  "on top of $subject",
  "with $subject on top",
  "with $subject",
  "right behind $subject",
  "in front of $subject",
  "in the highest tower",
  "in $their parents' room",
  "without knowing",
  "between the sofa cushions",
  "in $person's dreams",
  "around the world",
  "nowhere",
  "all alone",
  "in the basement",
  "yesterday"
];

var defaultAdjectives = [
  "a jelly-belly",
  "a bonkers",
  "a strong",
  "an obscenely muscular",
  "a meticulous",
  "a teeny-tiny",
  "a tipsy",
  "a ginormous",
  "a ridiculous",
  "a funny-looking",
  "an awesome",
  "a sly",
  "an old",
  "a kindly",
  "a bright",
  "a young",
  "a cute",
  "a sinister",
  "a slightly cock-eyed",
  "a transparent",
  "an invisible"
];

var defaultEndings = [
  ", right?",
  ", like I said.",
  ", just like yo' momma!",
  " again!",
  "- without flinching!",
  " as if it $was normal.",
  "... kinda.",
  " but later regretted it.",
  " and wouldn't stop dancing.",
  " then died.",
  " for you.",
  " for $subject.",
  ", resulting in the early demise of $subject.",
  " and didn't even realise it.",
  ". Then $person copied $them.",
  "... but nobody will believe me.",
  "... YOLO!",
  " and it made $them feel FAAANTastic!"
];
