var defaultGirls = [
  "Ploy",
  "Aras",
  "Dea",
  "Joey",
];

var defaultExtraGirls = [
  "Sigourney Weaver",
  "The Queen",
  "Cleopatra",

  "$person's gran",
  "$person's wife",
  "$person's sexy cousin",
  "$person's pet, $sentientObject,",
  "$person's mum",
  "the love of $their life",
  "the last of the dodos",
];

var defaultBoys = [
  "Kahfi",
  "Josh",
  "Ryan",
  "Reza",
];

var defaultExtraBoys = [
  "Santa",
  "Jesus",
  "Yoda",

  "$person's grandpapa",
  "$person's husband",
  "$person's dirty uncle",
  "$person's favourite $object",
  "some guy",
  "$their dad",
  "Cthulu",
  "$their brethren",
  "$their dog",
  "Uncle Saleh",
];

var defaultPrefixes = [
  " unfortunately",
  " likely",
  " briefly",
  " suddenly",
  " actually",
  " literally",
  ", honestly, ",
  ", like,",
  " really",
  " just",
  " recently",
  " drunkenly",
  " TOTALLY",
  " painfully",
  ", without a second thought,",
];

var defaultSentientObjects = [
  "$adj cow",
  "$adj man",
  "$adj woman",
  "$adj goblin",
  "$adj penguin",
  "$adj monkey",
  "$adj auntie",
  "$adj french chef",
  "$adj newt",
  "$adj kitty cat",
  "$adj criminal",
  "$adj dragon",
  "$adj patrolman",
  "$adj pervert",
  "$adj guy",
  "$adj multi-billionaire",
  "$adj hyena",
  "$adj pigeon",
];

var defaultPluralisedSentientObjects = [
  "a flock of $sentientObjects",
  "a herd of $sentientObjects",
  "a gabble of $sentientObjects",
  "a group of $sentientObjects",
];

var defaultInanimateObjects = [
  "$their lightsabre",
  "nothing",
  "some $sentientObject's poop",
  "an air guitar",
  "some fat",
  "a pen",
  "$their tongue",
  "a napkin",
  "$their face",
  "$adj octopus",
  "the door",
  "the chance of a life-time",
  "$adj rubber duckie",
  "the factory reset button",
  "$their blood rage",
  "$adj idiot",
  "a toaster",
  //"$their legend",
  "a death wish",
  "$their biggest goal in life",
  "a marketing idea",
  "$adj psychic",
  "a knife",
  "$their sandwich",
  "some lettuce",
  "some antidepressant drugs",
  "some corn cake",
  "$person's ashes",
  "$adj candlestick maker",
  "a coffee pot",
  "the national security agency",
  "a tank",
  "$their useless brakes",
  "the international law enforcement agency",
  "the sound barrier",
  "$adj private investor",
  "a stock car",
  "an elastic band",
  "$their mobile phone",
  "$their pistol",
  "some people in immense pain",
  "the idea $they suggested",
  "the Mona Lisa",
  "$their overly hairy legs",
  "$adj, irish cottage",
  "$their pocket flask",
  "some liquid oxygen",
  "a laser beam",
  "a dingle berry",
  "an electric furnace",
  "some dog poop",
  "the toilet seat",
  "a wrinkle",
  "some boiling water",
  "$their background story",
  "$their mood",
  "some nibblets",
  "a weed whacker",
];

var defaultPluralisedInanimateObjects = [
  "a metric-shit-tonne of $inanimateObjects",
  "a whole bunch o' $inanimateObjects",
  "a load of $inanimateObjects",
  "a few $inanimateObjects",
];

var defaultPlaces = [
  "on a mountain summit",
  "at the big game",
  "down the stairs",
  "in a coffin",
  "over the moon",
  "for $subject",
  "in place",
  "instead of $person",
  "in the bathroom",
  "followed by $anObject",
  "on top of $subject",
  "with $subject on top",
  "with $subject",
  "right behind $subject",
  "in front of $subject",
  "in the highest tower",
  "in $their parents' room",
  "without knowing",
  "between the sofa cushions",
  "in $person's dreams",
  "around the world",
  "in a little, plastic tub",
  "nowhere",
  "all alone",
  "in the basement",
  "in $person's basement",
  "in the TradeGecko office",
  "on level 3",
  "on the second floor",
  "yesterday",
  "down at the hunting grounds",
  "in the middle of the road",
  "around the local dojo",
  "throughout $boy's stag do",
  "in a sinking car",
  "in the middle of $girl's hen party",
  "through the library",
  "in a sess pit",
  "into a volcanic crater",
  "through the haunted graveyard",
  "on $person's grave",
  "running from $anObject",
  "between $person's legs",
  "in $their pants",
];

var defaultPersonableAdjectives = [
  "a jelly-belly",
  "a strong",
  "an obscenely muscular",
  "a tipsy",
  "a sly",
  "a kindly",
  "a young",
  "a sinister",
  "a slightly cock-eyed",
  "a friendly",
  "a sneaky",
  "a bat-shit-crazy",
  "a blathering",
  "a bonkers",
  "a bull headed",
  "a cocky",
  "a confused",
  "a cowardly",
  "a cruel-hearted",
  "a dead",
  "a demanding",
  "a drunken",
  "a fiercely-loyal",
  "a flirting",
  "another goddamned",
  "a greedy",
  "an hyperactive",
  "a maniacal",
  "a medicated",
  "a mentally impaired",
  "a naked",
  "a pea-brained",
  "a rebellious",
  "a sadistic",
  "a self-absorbed",
  "a self-centered",
  "a sick",
  "a slap happy",
  "a stubborn",
  "a vengeful",
  "a very tactful",
  "a violent",
  "a yapping",
  "an abusive",
  "an adulterous",
  "an alcoholic",
  "an idiotic",
  "an insane",
  "an insecure",
  "an overly attached",
  "an underhanded",
  "an up-to-no-good",
];

var defaultAdjectives = [
  ...defaultPersonableAdjectives,
  "a bearded",
  "a bright",
  "a costumed",
  "a crawly",
  "a cute",
  "a deep",
  "a disgusting",
  "a disrespectful",
  "a disturbing",
  "a domesticated",
  "a duck&NoBreak;-&NoBreak;like",
  "a fear&NoBreak;-&NoBreak;inspiring",
  "a fighting",
  "a filthy",
  "a flickering",
  "a fluffy",
  "a free&NoBreak;-&NoBreak;loading",
  "a frisky",
  "a frozen",
  "a funny&NoBreak;-&NoBreak;looking",
  "a GIANT",
  "a ginormous",
  "a godawful",
  "an hairless",
  "an harsh",
  "an hateful",
  "an haunting",
  "an hideous",
  "an high&NoBreak;-&NoBreak;end",
  "an hilarious",
  "an hot",
  "an house&NoBreak;-&NoBreak;broken",
  "a magical",
  "a massive",
  "a metal",
  "a meticulous",
  "a mischievous",
  "a misunderstood",
  "a narrow&NoBreak;-&NoBreak;minded",
  "a nighttime",
  "a painfully honest",
  "a really tough",
  "a ridiculous",
  "a rough&NoBreak;-&NoBreak;skinned",
  "a sexy",
  "a shaky",
  "a shivering",
  "a sickened",
  "a slimy",
  "a slippery",
  "a startled",
  "a startling",
  "a sticky",
  "a striped",
  "a stupid, little",
  "a talking",
  "a teeny&NoBreak;-&NoBreak;tiny",
  "a territorial",
  "a transparent",
  "a tripping",
  "a twisted",
  "a wild",
  "a zippy",
  "a zombie like",
  "an abnormal",
  "an angry",
  "an arrogant",
  "an at&NoBreak;-&NoBreak;the&NoBreak;-&NoBreak;ready",
  "an awesome",
  "an impertinent",
  "an impressive",
  "an indecent",
  "an infuriating",
  "an insanely creepy",
  "an internet worthy",
  "an invisible",
  "an offensive",
  "an old",
  "an out&NoBreak;-&NoBreak;of&NoBreak;-&NoBreak;control",
  "an outnumbered",
  "an ungodly",
  "an unholy",
  "a useless",
];

var defaultEndings = [
  " more frequently than before.",
  ", right?",
  ", like I said.",
  ", just like yo' momma!",
  " again!",
  "… twice!",
  " and then did it again.",
  " – without flinching!",
  " as if it $was normal.",
  "... kinda.",
  " but later regretted it.",
  " and wouldn't stop dancing.",
  " then died.",
  " for you.",
  " for $subject.",
  ", resulting in the early demise of $subject.",
  " and didn't even realise it.",
  ". Then $person copied $them.",
  "... but nobody will believe me.",
  "... YOLO!",
  " 😢",
  " 😕",
  " 🤭",
  " 🤣",
  " 😡",
  " and it made $them feel FAAANTastic!",
  " but $they $verb.",
  " resulting in the time that $subject $verb.",
  " with high spirits!",
  " with $their shakey hands.",
  ", and fistpumped such an EPIC result!",
  ", BUT IT WAS A MISTAKE!",
  ", yet $they won't admit it.",
  ". But $they'd never tell anyone.",
];
