const chordLabels = [
  "Augmented",
  "Augmented eleventh",
  "Augmented major seventh",
  "Augmented seventh",
  "Augmented sixth",
  "Diminished",
  "Diminished major seventh",
  "Diminished seventh",
  "Dominant",
  "Dominant eleventh",
  "Dominant minor ninth",
  "Dominant ninth",
  "Dominant parallel",
  "Dominant seventh",
  "Dominant seventh flat five",
  "Dominant seventh sharp nine",
  "Dominant thirteenth",
  "Dream",
  "Elektra",
  "Farben",
  "Half-diminished seventh",
  "Harmonic seventh",
  "Leading-tone triad",
  "Lydian",
  "Magic",
  "Major",
  "Major eleventh",
  "Major seventh",
  "Major seventh sharp eleventh",
  "Major sixth",
  "Major sixth ninth",
  "Major ninth",
  "Major thirteenth",
  "Mediant",
  "Minor",
  "Minor eleventh",
  "Minor major seventh",
  "Minor ninth",
  "Minor seventh",
  "Minor sixth",
  "Minor sixth ninth",
  "Minor thirteenth",
  "Mystic",
  "Neapolitan",
  "Ninth augmented fifth",
  "Ninth flat fifth",
  "Northern lights",
  "hexachord",
  "Petrushka",
  "Power",
  "Psalms",
  "Secondary dominant",
  "Secondary leading-tone",
  "Secondary supertonic",
  "Seven six",
  "Seventh suspension four",
  "So What",
  "Suspended",
  "Subdominant",
  "Subdominant parallel",
  "Submediant",
  "Subtonic",
  "Supertonic",
  "Thirteenth flat ninth",
  "Thirteenth flat ninth flat fifth",
  "Tonic counter parallel",
  "Tonic",
  "Tonic parallel",
  "Tristan",
  "Viennese trichord",
];

export default chordLabels;
