var defaultPrefixes = [
  " unfortunately",
  " likely",
  " finally",
  " accidentally",
  " briefly",
  " suddenly",
  " actually",
  " literally",
  ", honestly, ",
  ", like,",
  " really",
  " just",
  " recently",
  " drunkenly",
  " TOTALLY",
  " painfully",
  ", without a second thought, ",
];

var defaultSentientObjects = [
  "$adj cow",
  "$adj man",
  "$adj woman",
  "$adj thief",
  "$adj amish",
  "$adj louse",
  "$adj goblin",
  "$adj penguin",
  "$adj monkey",
  "$adj auntie",
  "$adj grouch",
  "$adj snuffaluffagus",
  "$adj french chef",
  "$adj trainer",
  "$adj traitor",
  "$adj newt",
  "$adj lapdog",
  "$adj jackass",
  "$adj gecko",
  "$adj freak",
  "$adj vegan",
  "a dickhead",
  "$adj master",
  "$adj druggie",
  "$adj kitty cat",
  "$adj puppy",
  "$adj criminal",
  "$adj dragon",
  "$adj patrolman",
  "$adj pervert",
  "$adj guy",
  "$adj gal",
  "$adj multi-billionaire",
  "$adj hyena",
  "$adj pigeon",
];

var defaultPluralisedSentientObjects = [
  "a flock of $sentientObjects",
  "a herd of $sentientObjects",
  "a gabble of $sentientObjects",
  "a group of $sentientObjects",
];

var defaultInanimateObjects = [
  "$their lightsabre",
  "$their new iPad",
  "nothing",
  "some $sentientObject’s poop",
  "an air guitar",
  "a fatty lump",
  "a pen",
  "a coffee cup",
  "a $object dip",
  "a dummy",
  "$object emulator",
  "$their tongue",
  "a napkin",
  "$their face",
  "$adj octopus",
  "the door",
  "the chance$s of a life-time",
  "$adj rubber duckie",
  "the factory reset button",
  "$their blood rage",
  "$adj idiot",
  "a toaster",
  "a death wish",
  "$their biggest goal$s in life",
  "a marketing idea",
  "$adj psychic",
  "a knife",
  "$their sandwich",
  "some lettuce",
  "some soap",
  "some antidepressant drugs",
  "some corn cake",
  "$person’s ashes",
  "$adj candlestick maker",
  "a coffee pot",
  "a light bulb",
  "the national security agency",
  "a tank",
  "$their useless brakes",
  "law enforcement agency",
  "sound barrier",
  "$adj private investor",
  "a stock car",
  "an elastic band",
  "$their mobile phone",
  "$their pistol",
  "some people$s in immense pain",
  "the idea$s $they suggested",
  "the Mona Lisa",
  "$their overly hairy legs",
  "$adj, irish cottage",
  "$their pocket flask",
  "some liquid oxygen",
  "a laser beam",
  "a dingle berry",
  "an electric furnace",
  "some dog poop",
  "the toilet seat",
  "a wrinkle",
  "some boiling water",
  "$their background story",
  "$their mood",
  "some nibblets",
  "a virus",
  "a weed whacker",
];

var defaultPluralisedInanimateObjects = [
  "a metric-shit-tonne of $inanimateObjects",
  "a whole bunch o’ $inanimateObjects",
  "a load of $inanimateObjects",
  "some $inanimateObjects",
  "a smattering of $inanimateObjects",
  "a small number of $inanimateObjects",
  "all o’ them $inanimateObjects",
];

var defaultPlaces = [
  "on a mountain summit",
  "at the big game",
  "down the stairs",
  "in a coffin",
  "over the moon",
  "for $subject",
  "in place",
  "instead of $person",
  "in the bathroom",
  "followed by $anObject",
  "on top of $subject",
  "with $subject on top",
  "with $subject",
  "right behind $subject",
  "in front of $subject",
  "in the highest tower",
  "in $their parents’ room",
  "without knowing",
  "between the sofa cushions",
  "in $person’s dreams",
  "around the world",
  "in a little, plastic tub",
  "nowhere",
  "all alone",
  "in the basement",
  "in $person’s basement ",
  "in the office",
  "around level 3",
  "on the second floor",
  "yesterday",
  "down at the hunting grounds",
  "in the middle of the road",
  "around the local dojo",
  "throughout $boy’s stag do",
  "in a sinking car",
  "in the middle of $girl’s hen party",
  "through the library",
  "in a sess pit",
  "in a volcanic crater",
  "in $person’s tomb",
  "through the haunted graveyard",
  "all over $person’s grave",
  ", running from $anObject",
  "between $person’s legs",
  "in $their pants",
];

var defaultPersonableAdjectives = [
  "a bat-shit-crazy",
  "a blathering",
  "a bonkers",
  "a bull headed",
  "a cocky",
  "a confused",
  "a cowardly",
  "a cruel-hearted",
  "a dead",
  "a demanding",
  "a drunken",
  "a dying",
  "a fiercely-loyal",
  "a flirting",
  "a friendly",
  "a greedy",
  "a jelly-belly",
  "a kindly",
  "a maniacal",
  "a medicated",
  "a mentally impaired",
  "a naked",
  "a pea-brained",
  "a rebellious",
  "a sadistic",
  "a self-absorbed",
  "a self-centered",
  "a sick",
  "a sinister",
  "a slap happy",
  "a slightly cock-eyed",
  "a sly",
  "a sneaky",
  "a strong",
  "a stubborn",
  "a tipsy",
  "a vengeful",
  "a very tactful",
  "a violent",
  "a yapping",
  "a young",
  "an abusive",
  "an adulterous",
  "an alcoholic",
  "an hyperactive",
  "an idiotic",
  "an insane",
  "an insecure",
  "a talkative",
  "a laughing",
  "an obscenely muscular",
  "an overly attached",
  "an underhanded",
  "a nocturnal",
  "an angry",
  "an up-to-no-good",
  "another goddamned",
  "an emotional",
];

var defaultAdjectives = [
  ...defaultPersonableAdjectives,
  "a bearded",
  "a bright",
  "a costumed",
  "a crawly",
  "a cute",
  "a deep",
  "a disgusting",
  "a disrespectful",
  "a disturbing",
  "a domesticated",
  "a duck&NoBreak;-&NoBreak;like",
  "a fear&NoBreak;-&NoBreak;inspiring",
  "a fighting",
  "a filthy",
  "a flickering",
  "a fluffy",
  "a free&NoBreak;-&NoBreak;loading",
  "a frisky",
  "a frozen",
  "a funny&NoBreak;-&NoBreak;looking",
  "a GIANT",
  "a ginormous",
  "a godawful",
  "a dainty",
  "a hairless",
  "a harsh",
  "a hateful",
  "a haunting",
  "a hideous",
  "a high&NoBreak;-&NoBreak;end",
  "a hilarious",
  "a hot",
  "a house&NoBreak;-&NoBreak;broken",
  "a magical",
  "a massive",
  "a dirty",
  "a metal",
  "a meticulous",
  "a mischievous",
  "a misunderstood",
  "a narrow&NoBreak;-&NoBreak;minded",
  "a painfully honest",
  "a perverted",
  "a really tough",
  "a ridiculous",
  "a rough&NoBreak;-&NoBreak;skinned",
  "a sexy",
  "a shaky",
  "a shivering",
  "a sickened",
  "a slimy",
  "a slippery",
  "a startled",
  "a startling",
  "a sticky",
  "a striped",
  "a stupid, little",
  "a talking",
  "a teeny&NoBreak;-&NoBreak;tiny",
  "a territorial",
  "a transparent",
  "a tripping",
  "a twisted",
  "a wild",
  "a zippy",
  "a zombie like",
  "an abnormal",
  "an arrogant",
  "an at&NoBreak;-&NoBreak;the&NoBreak;-&NoBreak;ready",
  "an awesome",
  "an electric",
  "an impertinent",
  "an impressive",
  "an indecent",
  "an infuriating",
  "an insanely creepy",
  "an internet worthy",
  "an invisible",
  "an offensive",
  "an old",
  "an out&NoBreak;-&NoBreak;of&NoBreak;-&NoBreak;control",
  "an outnumbered",
  "an ungodly",
  "an unholy",
  "a useless",
];

var defaultAdverbs = [
  "stupidly",
  "annoyingly",
  "very",
  "oddly",
  "kinda",
  "accidentally",
];

var defaultEndings = [
  " – without flinching!",
  " again!",
  " and didn’t even realise it.",
  " and it made $them feel FAAANTastic!",
  " and kept laughing manically.",
  " and then did it again.",
  " and wouldn’t stop dancing.",
  " as if it $was normal.",
  " but $they $didSomething.",
  " but later regretted it.",
  " for $person.",
  " for $subject.",
  " for you.",
  " more frequently than before.",
  " in $person’s dream.",
  " in peace.",
  " resulting in the time that $subject $didSomething.",
  " then died.",
  " upside-down.",
  " with $person.",
  " with $their shakey hands.",
  " with high spirits!",
  ", and fistpumped such an EPIC result!",
  ", BUT IT WAS A MISTAKE!",
  ", coincidentally.",
  ", just like yo’ momma!",
  ", like I said.",
  ", resulting in the early demise of $subject.",
  ", right?",
  ", but don’t tell $person I told you!",
  ", yet $they won’t admit it.",
  ". But $they’d never tell anyone.",
  ". No rugrats!",
  ". Then $person copied $them.",
  ", then $person $didSomething.",
  ". Wait, no, that was $person!",
  "… but nobody will believe me.",
  "… kinda.",
  "… on a Windows machine!",
  "… twice!",
  "… YOLO!",
  " while tripping.",
  " 😢",
  " 😕",
  " 🤭",
  " 🤣",
  " 😡",
  " 🤮",
  " 👏",
];
