export const items = [
  { name: "Alan Z", image: "./i/Alan Z.jpg" },
  {
    name: "Arnaud Michel Jacques Lago",
    image: "./i/Arnaud Michel Jacques Lago.jpg",
  },
  { name: "Brandon Jie Yi Lam", image: "./i/Brandon Jie Yi Lam.jpg" },
  { name: "Brandon Ong", image: "./i/Brandon Ong.png" },
  { name: "Brook Jordan", image: "./i/Brook Jordan.jpg" },
  { name: "Eduard Nabokov", image: "./i/Eduard Nabokov.jpg" },
  { name: "Fil Mihaylov", image: "./i/Fil Mihaylov.png" },
  { name: "Hung Viet Nguyen", image: "./i/Hung Viet Nguyen.jpg" },
  { name: "Ivan Petkov", image: "./i/Ivan Petkov.jpg" },
  { name: "Kakali Basak", image: "./i/Kakali Basak.jpg" },
  { name: "Katya Daskalova", image: "./i/Katya Daskalova.jpg" },
  {
    name: "Marcellus Reinaldo Jodihardja",
    image: "./i/Marcellus Reinaldo Jodihardja.jpg",
  },
  { name: "Marco Mandrioli", image: "./i/Marco Mandrioli.jpg" },
  { name: "Matt Yang", image: "./i/Matt Yang.jpg" },
  { name: "Minsung Cho", image: "./i/Minsung Cho.jpg" },
  { name: "Namith", image: "./i/Namith.jpg" },
  { name: "Nicholas Tan Xuan", image: "./i/Nicholas Tan Xuan.jpg" },
  { name: "Olzhas Kaiyrakhmet", image: "./i/Olzhas Kaiyrakhmet.jpg" },
  { name: "Panteley Boyadjiev", image: "./i/Panteley Boyadjiev.jpg" },
  { name: "Plamen", image: "./i/Plamen.png" },
  { name: "Quanjie Yang", image: "./i/Quanjie Yang.jpg" },
  { name: "Rajnish Kumar", image: "./i/Rajnish Kumar.png" },
  { name: "Robin Yeh", image: "./i/Robin Yeh.jpg" },
  {
    name: "Sadaananth Anbucheliyan",
    image: "./i/Sadaananth Anbucheliyan.png",
  },
  { name: "Sarah Neo", image: "./i/Sarah Neo.jpg" },
  { name: "Sergei Stepanov", image: "./i/Sergei Stepanov.jpg" },
  { name: "Shen Rui Chong", image: "./i/Shen Rui Chong.jpg" },
  { name: "Stacey Ng", image: "./i/Stacey Ng.jpg" },
  {
    name: "Thanh Tam Hoang",
    image: "./i/Thanh Tam Hoang.jpg",
  },
  { name: "Tian Fu Tan", image: "./i/Tian Fu Tan.jpg" },
  { name: "Tudor Gergely", image: "./i/Tudor Gergely.jpg" },
  { name: "Wan Jou Lim", image: "./i/Wan Jou Lim.jpg" },
  {
    name: "Wee Kiat Clarence Ang",
    image: "./i/Wee Kiat Clarence Ang.jpg",
  },
  { name: "Wei Jian Chen", image: "./i/Wei Jian Chen.jpg" },
  {
    name: "William Kar Hoong Yoong",
    image: "./i/William Kar Hoong Yoong.jpg",
  },
  {
    name: "Zizhang Ai",
    image: "./i/Zizhang Ai.jpg",
  },
];
